export const airlines = [
  { code: "AA", name: "American Airlines" },
  { code: "DL", name: "Delta Air Lines" },
  { code: "UA", name: "United Airlines" },
  { code: "SW", name: "Southwest Airlines" },
  { code: "BA", name: "British Airways" },
  { code: "LH", name: "Lufthansa" },
  { code: "AF", name: "Air France" },
  { code: "KL", name: "KLM Royal Dutch Airlines" },
  { code: "EK", name: "Emirates" },
  { code: "QR", name: "Qatar Airways" },
  { code: "SQ", name: "Singapore Airlines" },
  { code: "CX", name: "Cathay Pacific" },
  { code: "JL", name: "Japan Airlines" },
  { code: "NH", name: "All Nippon Airways" },
  { code: "AI", name: "Air India" },
  { code: "9W", name: "Jet Airways" },
  { code: "6E", name: "IndiGo" },
  { code: "SG", name: "SpiceJet" },
];
